# http://www.appveyor.com/docs/appveyor-yml
#
# To setup AppVeyor for your own personal repositories do the following:
# - Sign up
# - Add a new project
# - Select Git and fill in the Git clone URL
# - Setup a Git hook as explained in
#   https://github.com/appveyor/webhooks#installing-git-hook
# - Check 'Settings > General > Skip branches without appveyor.yml'
# - Check 'Settings > General > Rolling builds'
# - Setup the global or project notifications to your liking
#
# Note that kicking (or restarting) a build via the web UI will not work, as it
# will fail to find appveyor.yml .  The Git hook is the most practical way to
# kick a build.
#
# See also:
# - http://help.appveyor.com/discussions/problems/2209-node-grunt-build-specify-a-project-or-solution-file-the-directory-does-not-contain-a-project-or-solution-file
# - http://help.appveyor.com/discussions/questions/1184-build-config-vs-appveyoryaml

version: '{build}'

branches:
  except:
  - /^travis.*$/

# Don't download the full Mesa history to speed up cloning.  However the clone
# depth must not be too small, otherwise builds might fail when lots of patches
# are committed in succession, because the desired commit is not found on the
# truncated history.
#
# See also:
# - https://www.appveyor.com/blog/2014/06/04/shallow-clone-for-git-repositories
clone_depth: 100

# https://www.appveyor.com/docs/build-environment/#build-worker-images
os: Visual Studio 2015

environment:
  PYTHON_HOME: C:\Python36
  matrix:
  - MINGW_HOME: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32
  - MINGW_HOME: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
  - MSVC_ARCH: x86
  - MSVC_ARCH: x86_amd64

matrix:
  fast_finish: true

install:
# Setup Python 3
- set Path=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%Path%
- pip --version
# Install Mako
- pip install meson
- meson --version
# Install Ninja
- cinst -y ninja
- ninja --version
# Setup MinGW
- if not "%MINGW_HOME%"=="" set Path=%MINGW_HOME%\bin;%Path%
# Setup MSVC
- if not "%MSVC_ARCH%"=="" set call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %MSVC_ARCH%

build_script:
- meson . build
- ninja -C build


# It's possible to setup notification here, as described in
# http://www.appveyor.com/docs/notifications#appveyor-yml-configuration , but
# doing so would cause the notification settings to be replicated across all
# repos, which is most likely undesired.  So it's better to rely on the
# Appveyor global/project notification settings.
